name: CI
'on':
  push:
    branches:
      - custom-branch-name
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'postgres:latest'
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: your_database_user
          POSTGRES_PASSWORD: postgressql123
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run database migrations
        run: 'bundle exec rails db:migrate'
      - name: Run tests
        run: bundle exec rspec
      - name: Run Brakeman
        run: bundle exec brakeman
      - name: Run ESLint
        run: npm run eslint
